# Generated by Django 4.0.3 on 2022-04-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Education name')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Skill name')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(null=True, to='resume.education'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill',
            field=models.ManyToManyField(null=True, to='resume.skill'),
        ),
    ]
