# Generated by Django 4.0.3 on 2022-04-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education_skill_resume_education_resume_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Work name')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.TextField(unique=True, verbose_name='Education name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.TextField(unique=True, verbose_name='Skill name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience',
            field=models.ManyToManyField(null=True, to='resume.workexperience'),
        ),
    ]
