# Generated by Django 4.0.3 on 2022-04-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_workexperience_resume_work_experience_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(to='resume.education'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skill',
            field=models.ManyToManyField(to='resume.skill'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_experience',
            field=models.ManyToManyField(to='resume.workexperience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='language',
            field=models.ManyToManyField(to='resume.language'),
        ),
    ]
