# Generated by Django 4.0.3 on 2022-04-19 20:31

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(null=True, upload_to=apps.account.models.get_profile_path),
        ),
    ]
