# Generated by Django 4.0.3 on 2022-04-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_user_auth_provider_user_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
    ]
